### ISSUE TITLE
Failed to run evaluate_kitti.py

### ISSUE THREAD

**Issue by Tavish-777** [princeton-vl/DPVO#77]
![image](https://github.com/user-attachments/assets/ace71319-2941-46a1-9310-8a93e163f454)
When I run this script, it gets stuck at this point and stops responding. After debugging, I found that it gets stuck at the queue.get() step, but I don't have any clues on how to solve this issue. I hope the author can provide some assistance.

**Comment by lahavlipson** [comment]
The dataloading process probably crashed because one of the expected files is not present. By default, the code expects the first sequence to be:
- images: `datasets/KITTI/dataset/sequences/00/image_2/*.png`
- poses: `datasets/KITTI/poses/00.txt`
- intrinsics: `datasets/KITTI/dataset/sequences/00/calib.txt`

which should be what you get if you unpack the [kitti odometry files ](https://www.cvlibs.net/datasets/kitti/eval_odometry.php)under `datasets/KITTI`

**Comment by Tavish-777** [comment]
Thanks, now my dataloading is fine, able to read data , but I have a new problem;
<img width="574" alt="1727230109044" src="https://github.com/user-attachments/assets/d56d0bf5-bef0-4880-ac0d-d6c23ca27e30">
It will interrupt unexpectedly

**Comment by Tavish-777** [comment]
I tried deleting and reinstalling the environment, but it seems that the situation has gotten worse.
![image](https://github.com/user-attachments/assets/d7f8baf6-a6c6-4966-bbb9-edd0ade92940)
It seems that there is a problem with the C++ part, but I don't know how to debug it.
